# Generated by Django 2.2.6 on 2021-02-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeView',
            new_name='Recipe',
        ),
    ]
