# Generated by Django 2.2.6 on 2021-02-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description_short',
            field=models.CharField(default='xxx', max_length=128),
            preserve_default=False,
        ),
    ]
