# Generated by Django 2.2.6 on 2021-02-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0002_auto_20210222_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description_short',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
